In [1]:
import tensorflow as tf
import numpy as np

char_rdic = ['h', 'e', 'l', 'o']
char_dic = {w: i for i, w in enumerate(char_rdic)}
ground_truth = [char_dic[c] for c in 'hello']
x_data = tf.one_hot(ground_truth[:-1], len(char_dic))

rnn_size = len(char_dic)
batch_size = 1
#rnn_cell = tf.nn.rnn_cell.BasicRNNCell(num_units = rnn_size)
rnn_cell = tf.nn.rnn_cell.BasicLSTMCell(num_units = rnn_size)
initial_state = rnn_cell.zero_state(batch_size, tf.float32)

x_split = tf.split(0, len(char_dic), x_data)
outputs, state = tf.nn.rnn(cell = rnn_cell, inputs = x_split, initial_state = initial_state)

logits = tf.reshape(tf.concat(1, outputs), [-1, rnn_size])
targets = tf.reshape(ground_truth[1:], [-1])
weights = tf.ones([len(char_dic) * batch_size])

loss = tf.nn.seq2seq.sequence_loss_by_example([logits], [targets], [weights])
cost = tf.reduce_sum(loss) / batch_size
train_op = tf.train.RMSPropOptimizer(0.01, 0.9).minimize(cost)
#train_op = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

with tf.Session() as sess:
    tf.initialize_all_variables().run()
    for i in range(1001):
        sess.run(train_op)
        result = sess.run(tf.argmax(logits, 1))
        if i % 200 == 0:
            print(result, [char_rdic[t] for t in result], sess.run(cost))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[2 1 3 3] ['l', 'e', 'o', 'o'] 5.52686
[1 2 2 3] ['e', 'l', 'l', 'o'] 2.45645
[1 2 2 3] ['e', 'l', 'l', 'o'] 2.18083
[1 2 2 3] ['e', 'l', 'l', 'o'] 2.12414
[1 2 2 3] ['e', 'l', 'l', 'o'] 2.09451
[1 2 2 3] ['e', 'l', 'l', 'o'] 2.0756
